### PR TITLE
Fix compilation error and modernize

### PR DESCRIPTION
**Pull request by gewarren**
(Hide whitespace changes.)

Compilation error introduced by https://github.com/dotnet/dotnet-api-docs/pull/8741 (by me).

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

Let's :shipit:
